{
  parserClass="org.setms.sew.intellij.SewParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="Sew"
  psiImplClassSuffix="Impl"
  psiPackage="org.setms.sew.intellij"
  psiImplPackage="org.setms.sew.intellij"
  elementTypeHolderClass="org.setms.sew.intellij.SewElementTypes"
  elementTypeClass="org.setms.sew.intellij.SewElementType"
  tokenTypeClass="org.setms.sew.intellij.SewTokenType"
  tokens=[
    COMMA=","
    COMMENT="comment"
    DOT="."
    EQ="="
    IDENTIFIER="identifier"
    LBRACE="{"
    LBRACK="["
    LPAREN="("
    NAME="name"
    PACKAGE="package"
    RBRACE="}"
    RBRACK="]"
    RPAREN=")"
    TYPE="type name"
    WHITE_SPACE="white space"
  ]
}

sewFile ::= scope? &TYPE object+

scope ::= PACKAGE qualifiedName NEWLINE

qualifiedName ::= IDENTIFIER (DOT IDENTIFIER)*

object ::= TYPE objectName LBRACE NEWLINE property* RBRACE NEWLINE

objectName ::= NAME

property ::= propertyName EQ (item | list) NEWLINE

propertyName ::= IDENTIFIER

list ::= LBRACK NEWLINE? (item (COMMA NEWLINE? item)*)? NEWLINE? RBRACK

item ::= objectName | STRING | typedName

typedName ::= TYPE LPAREN objectName RPAREN
