package org.setms.swe.domain.model.sdlc.technology;

/** Code generated by a generator like {@link UnitTestGenerator}. */
public record GeneratedCode(String fileName, String relativePath, String content) {}
