name: Build and Release IntelliJ Plugin

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build IntelliJ plugin
        run: ./gradlew check :intellij:buildPlugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: intellij/build/distributions/*.zip
          tag_name: latest
          name: "Development Build (Latest)"
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
