name: Build and Release IntelliJ Plugin

concurrency: build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Restore Pitest analysis cache
        id: restore-pitest-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-pitest-${{ github.sha }}
          restore-keys: ${{ runner.os }}-pitest-
          path: ~/.pitest/cache/*_pitest_history.bin

      - name: Build IntelliJ plugin
        run: ./gradlew check :intellij:buildPlugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: intellij/build/distributions/*.zip
          tag_name: latest
          name: "Development Build (Latest)"
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Save Pitest analysis Cache
        uses: actions/cache/save@v4
        with:
          key: 'pitest'
          path: ~/.pitest/cache/*_pitest_history.bin